### ISSUE TITLE
Xbox one controller starts to power on but never completes.

### ISSUE THREAD

**Issue by superskyman64** [lloeki/xbox_one_controller#4]
Starts to power on, on the last time it blinks it just fades out. Never connects, I have been trying different drivers and programs for an hour. What do I do?
Also: If this is a program, where do I find it?

**Comment by lloeki** [comment]
> Starts to power on, on the last time it blinks it just fades out. Never connects, I have been trying different drivers and programs for an hour.

If you did not install a driver or use a program that knows how to talk to the controller this is expected behaviour: the controller just has no one to talk to so it just shuts itself off.

> Also: If this is a program, where do I find it

This is a kernel driver. I don't know if the kext still works on a recent macOS, and I don't have a developer certificate anymore. From there you're on your own, sorry.
