### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by jbonnett92** [lloeki/xbox_one_controller#5]
Hi,
I get this when installing:
![Install failed](https://i.imgur.com/P3shmSL.png)

Thanks,
Jamie

**Comment by lloeki** [comment]
Reproduced on High Sierra here. It seems like `boot-args` access may be blocked, possibly for improved security, since Sierra.

See that question on [Ask Different](https://apple.stackexchange.com/questions/256138/trying-to-set-boot-args-with-nvram-gets-general-error-on-sierra/269777):

> Starting with macOS Sierra, you must be booted to the recovery partition to run this command.

I don't know if the kext still works on a recent macOS, and I don't have a developer certificate anymore. From there you're on your own, sorry.
